name = "motiv-app"
main = "workers/index.ts"
compatibility_date = "2024-01-01"

# Environment variables (for local dev)
[vars]
FRONTEND_URL = "http://localhost:4321"
ENVIRONMENT = "development"

# Development settings
[env.development]
vars = { ENVIRONMENT = "development" }

# D1 Database
[[env.development.d1_databases]]
binding = "DB"
database_name = "motiv-db"
database_id = "796f0535-9ae0-4661-bd81-0541204d738a"

# KV Namespaces for sessions
[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "3b411963c66e49308726624a1c37bd03"

# R2 Storage for media
[[env.development.r2_buckets]]
binding = "MEDIA"
bucket_name = "motiv-media"

# Preview settings (for PR previews)
[env.preview]
name = "motiv-app-preview"
vars = { ENVIRONMENT = "preview" }

# Preview bindings (same as dev for now)
[[env.preview.d1_databases]]
binding = "DB"
database_name = "motiv-db"
database_id = "796f0535-9ae0-4661-bd81-0541204d738a"

[[env.preview.kv_namespaces]]
binding = "SESSIONS"
id = "3b411963c66e49308726624a1c37bd03"

[[env.preview.r2_buckets]]
binding = "MEDIA"
bucket_name = "motiv-media"

# Production settings
[env.production]
name = "motiv-app"
vars = { ENVIRONMENT = "production", FRONTEND_URL = "https://motiv.pages.dev" }

# Production bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "motiv-db"
database_id = "796f0535-9ae0-4661-bd81-0541204d738a"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "3b411963c66e49308726624a1c37bd03"

[[env.production.r2_buckets]]
binding = "MEDIA"
bucket_name = "motiv-media"